"""create table

Revision ID: 060fbf9ba5fb
Revises: 
Create Date: 2023-04-09 23:35:49.825043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060fbf9ba5fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
