"""upgrade table

Revision ID: 6f904894d831
Revises: 060fbf9ba5fb
Create Date: 2023-04-09 23:52:44.058751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f904894d831'
down_revision = '060fbf9ba5fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('id2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'id2')
    # ### end Alembic commands ###
